name: PackSquash
on:
  push:
    tags:
      - '**'
jobs:
  packsquash:
    name: PackSquash
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Squash
        uses: ComunidadAylas/PackSquash-action@v4
        with:
          packsquash_version: 'v0.4.0'
          options: |
            pack_directory = '.'
            output_file_path = '/tmp/pack.zip'
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: /tmp/pack.zip